// ngShare_frontend/src/components/Login.jsx
import React from 'react';
import GoogleLogin from 'react-google-login';
import { useNavigate } from 'react-router-dom';
import { FcGoogle } from 'react-icons/fc';
import shareVideo from '../assets/share.mp4';
import logo from '../assets/logowhite.png';

const Login = () => {

    const responseGoogle = (response) => {
        console.log(response);
    }
    return (
        <div className='flex justify-start items-center flex-col h-screen'>
            <div className='relative w-full h-full'>
                <video 
                src={shareVideo}
                type="video/mp4"
                loop
                controls={false}
                muted
                autoPlay
                className='w-full h-full object-cover' />

                <div className='absolute flex flex-col justify-center items-center top-0 right-0 left-0 bottom-0 bg-blackOverlay'>
                    <div className='p-5'>
                        <img src={logo} width="130px" alt='logo' />
                    </div>
                    <div className='shadow-2xl'>
                        <GoogleLogin 
                        clientId=''
                        render={(renderProps) => (
                            <button 
                            type='button'
                            className='flex justify-center items-center p-3 rounded-lg bg-white cursor-pointer outline-none'
                            onClick={renderProps.onClick}
                            disabled={renderProps.disabled} >
                                <FcGoogle className='mr-4'/> Sign in with Google
                            </button>
                        )}
                        onSuccess={responseGoogle}
                        onFailure={responseGoogle}
                        cookiePolicy='single_host_policy'
                        />
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Login

// ngShare_frontend/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { GoogleLoginProvider, SocialAuthService } from 'angularx-social-login';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  constructor(private router: Router, private socialAuthService: SocialAuthService) { }

  ngOnInit(): void {
  }

  loginWithGoogle(): void {
    this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID).then(
      (data) => {
        localStorage.setItem('user', JSON.stringify(data));
        this.router.navigate(['home']);
      }
    ).catch((err) => {
      console.warn(err);
    })
  }

}

<div class="d-flex justify-start items-center flex-column vh-100">
  <div class="position-relative w-100 h-100">
    <video class="video-cover" loop autoplay muted oncanplay="this.play()" onloadedmetadata="this.muted = true">
      <source src="../../assets/share.mp4" type="video/mp4">
    </video>
    <div class="position-absolute d-flex flex-column justify-content-center align-items-center top-0 right-0 left-0 bottom-0 w-100 bg-dark-custom">
      <div class="p-3">
        <img src="../../assets/NgShare-logos_transparent1.png" alt="logo" style="width: 150px">
      </div>
      <div >
        <div class="col s12 m6 offset-m3 center-align bg-white rounded-pill">
          <a class="oauth-container btn darken-4 white text-dark d-flex" (click)="loginWithGoogle()" style="text-transform:none">
              <div class="left">
                  <img width="20px" style="margin-right:8px" alt="Google sign-in" 
                      src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png" />
              </div>
              Login with Google
          </a>
      </div>
      </div>
    </div>
    
  </div>
</div>
